# Generated by Django 4.0.2 on 2022-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_draft_alter_author_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
